"""add index to state field (relation user-word)

Revision ID: 06b23b86cbda
Revises: 03371b167d3f
Create Date: 2024-10-25 17:15:33.487435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b23b86cbda'
down_revision: Union[str, None] = '03371b167d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_word_relations_state'), 'user_word_relations', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_word_relations_state'), table_name='user_word_relations')
    # ### end Alembic commands ###
