"""empty message

Revision ID: 2819373830bd
Revises: dfbd3be3bdac
Create Date: 2024-10-14 17:07:31.059328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2819373830bd'
down_revision: Union[str, None] = 'dfbd3be3bdac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dayly_goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dayly_goal')
    # ### end Alembic commands ###
